[package]
name = "axum_cudarc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.12"
cudarc = "0.9.2"
tokio = { version = "1.26.0", features = ["rt-multi-thread", "macros"] }
